name: bandu_business
description: "Bandu Business"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1
  rxdart: ^0.28.0
  url_launcher: ^6.3.2
  bounce: ^1.0.2
  google_fonts: ^6.3.2
  fluttertoast: ^9.0.0
  mask_text_input_formatter: ^2.9.0
  yandex_mapkit: ^4.2.1
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  flutter_bloc: ^9.1.1
  pinput: ^5.0.2
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  http_parser: ^4.1.2
  http: ^1.6.0
  geolocator: ^14.0.2
  intl: ^0.20.2
  in_app_review: ^2.0.11
  flutter_rating: ^2.0.2
  share_plus: ^12.0.1
  dropdown_flutter: ^1.0.3
  qr_code_scanner_plus: ^2.0.14
  modal_bottom_sheet: ^3.0.0
  geocoding: ^4.0.0
  fl_chart: ^1.1.1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/fonts/
    - assets/fonts/spring/
    - assets/images/

  fonts:
    - family: Fontspring-DEMO
      fonts:
        - asset: assets/fonts/spring/Fontspring-DEMO-freigeist-black.otf
          weight: 800
